name: macOS

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "scripts/**"
      - "LICENSE.md"
      - "README.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "scripts/**"
      - "LICENSE.md"
      - "README.md"

  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-15-intel

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Check Clang version
        run: |
          clang -v

      # - name: Setup Xmake
      #   uses: xmake-io/github-action-setup-xmake@v1
      #   with:
      #     xmake-version: latest

      - name: Compile with Clang (Intel)
        run: |
          xmake f -c -p cross --cross=x86_64-apple-macos11.0 --toolchain=clang
          xmake -rv

      - name: Compile with Clang (Apple Silicon)
        run: |
          xmake f -c -p cross --cross=aarch64-apple-macos11.0 --toolchain=clang
          xmake -rv
